

CREATE SEQUENCE  "EDOC_RECEIVE_MISSION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "EDOC_RECEIVE_MISSION_HIS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "MISSION_COMBINE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "EDOC_RECEIVE_FILE_ATTACH_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

create table EDOC_RECEIVE_MISSION
(
    EDOC_RECEIVE_MISSION_ID NUMBER not null
        constraint EDOC_RECEIVE_MISSION_PK
            primary key,
    IDENTIFY_FROM_CODE      VARCHAR2(500),
    IDENTIFY_FROM_NAME      VARCHAR2(500),
    CODE                    VARCHAR2(500),
    DOCUMENT_TYPE           NUMBER,
    STATUS_SYS              NUMBER(1),
    STATUS_UPDATE           NUMBER(38),
    DATE_PUBLISH            DATE,
    CONTENT                 VARCHAR2(500),
    CTCT                    VARCHAR2(500),
    DOCUMENT_CODE           VARCHAR2(2000),
    CREATE_DEPT_CODE        VARCHAR2(2000),
    CREATE_DEPT_NAME        VARCHAR2(2000),
    CREATE_BY               NUMBER,
    CREATE_TIME             DATE,
    FOLLOW_IDENTIFY_CODE    VARCHAR2(2000),
    FOLLOW_DEPT_NAME        VARCHAR2(2000),
    MISSION_TYPE            NUMBER(38),
    DEADLINE                DATE,
    NUMBER_URGE             NUMBER(38),
    TYPE_MISSION            NUMBER(38),
    FOLLOW_NAME             VARCHAR2(2000),
    CONTACT                 VARCHAR2(2000),
    SYNCHRONIZED_DATE       DATE,
    TO_IDENTIFY_CODE        VARCHAR2(2000),
    TO_DEPT_NAME            VARCHAR2(2000),
    IS_SEND                 NUMBER(1),
    SCOPE                   VARCHAR2(2000),
    DOCUMENT_ID             NUMBER,
    ABSTRACT                VARCHAR2(2000),
    PUBLISH_AGENCY_NAME     VARCHAR2(2000),
    DATE_CREATE             DATE,
    SECURITY_TYPE_ID        NUMBER(38),
    SIGNER_NAME             VARCHAR2(2000),
    POS_NAME                VARCHAR2(2000),
    EDXML                   clob
);

create table EDOC_RECEIVE_MISSION_HIS
(
    EDOC_RECEIVE_MISSION_HIS_ID    NUMBER not null
        constraint EDOC_RECEIVE_MISSION_HIS_PK
            primary key,
    EDOC_RECEIVE_MISSION_ID        NUMBER,
    HISTORY_ID NUMBER,
    CODE              VARCHAR2(200),
    TYPE              NUMBER,
    REPORT_CONTENT    VARCHAR2(1000),
    STATUS            NUMBER,
    DEADLINE_OLD      TIMESTAMP(6),
    DEADLINE_NEW      TIMESTAMP(6),
    UPDATE_BY_ID      NUMBER,
    UPDATE_BY         VARCHAR2(200),
    UPDATE_TIME       TIMESTAMP(6),
    TO_IDENTIFY_CODE  NVARCHAR2(200),
    TO_DEPT_NAME      NVARCHAR2(300)
);

create table EDOC_RECEIVE_FILE_ATTACH
(
    EDOC_RECEIVE_FILE_ATTACH_ID    NUMBER not null
        constraint EDOC_RECEIVE_FILE_ATTACH_PK
            primary key,
    MISSION_ID        NUMBER,
    MISSION_HIS_ID NUMBER,
    FILE_ID              VARCHAR2(200),
    TYPE_ID              NUMBER,
    TEN_FILE    VARCHAR2(1000),
    IS_SYNC            NUMBER default 0
);

alter table attachs add id_file_dinh_kem number;
alter table mission_his add is_sent number;
alter table mission_his add message_log varchar2(500);
alter table mission_his add send_date TIMESTAMP(6);


truncate table EDOC_RECEIVE_MISSION;
alter table EDOC_RECEIVE_MISSION modify (create_by varchar2(300));

alter table EDOC_RECEIVE_FILE_ATTACH add file_path varchar2(500);

